Repository Kostia1507/KaizenChat, pull requests merged in 2023-04, with the labels that each got.

#1 feature/TASK-3_implement-auth-system
  README.md
  pom.xml
  src/main/java/com/example/kaizenchat/controller/AuthController.java
  src/main/java/com/example/kaizenchat/dto/RefreshTokenRequest.java
  src/main/java/com/example/kaizenchat/dto/UserLoginRequest.java
  src/main/java/com/example/kaizenchat/dto/UserRegistrationRequest.java
  src/main/java/com/example/kaizenchat/entity/RoleEntity.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
  src/main/java/com/example/kaizenchat/exception/InvalidRequestDataException.java
  src/main/java/com/example/kaizenchat/repository/RoleRepository.java
  src/main/java/com/example/kaizenchat/repository/UserRepository.java
  src/main/java/com/example/kaizenchat/security/SpringSecurityConfig.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTFilter.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTProvider.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTType.java
  src/main/java/com/example/kaizenchat/security/jwt/UserDetailsImpl.java
  src/main/java/com/example/kaizenchat/security/jwt/UserDetailsServiceImpl.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: documentation, enhancement, help wanted

#3 feature/TASK-6_create-entities
  src/main/java/com/example/kaizenchat/entity/ChatEntity.java
  src/main/java/com/example/kaizenchat/entity/GroupChatOptionsEntity.java
  src/main/java/com/example/kaizenchat/entity/MessageEntity.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
Labels: enhancement, help wanted

#4 feature/TASK-9_develop-message-service
  src/main/java/com/example/kaizenchat/entity/MessageEntity.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
  src/main/java/com/example/kaizenchat/exception/ChatNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/MessageNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundInChatException.java
  src/main/java/com/example/kaizenchat/exception/UserViolationPermissionsException.java
  src/main/java/com/example/kaizenchat/repository/ChatRepository.java
  src/main/java/com/example/kaizenchat/repository/MessageRepository.java
  src/main/java/com/example/kaizenchat/service/MessageService.java
  src/main/java/com/example/kaizenchat/service/impl/MessageServiceImpl.java
Labels: enhancement

#5 feature/TASK-9_develop-chat-service
  src/main/java/com/example/kaizenchat/dto/AddMemberToChatRequest.java
  src/main/java/com/example/kaizenchat/dto/DuoChatCreationRequest.java
  src/main/java/com/example/kaizenchat/dto/GroupChatCreationRequest.java
  src/main/java/com/example/kaizenchat/entity/ChatEntity.java
  src/main/java/com/example/kaizenchat/exception/ChatAlreadyExistsException.java
  src/main/java/com/example/kaizenchat/exception/UserViolationPermissionsException.java
  src/main/java/com/example/kaizenchat/model/ChatType.java
  src/main/java/com/example/kaizenchat/model/DuoChat.java
  src/main/java/com/example/kaizenchat/model/GroupChat.java
  src/main/java/com/example/kaizenchat/repository/ChatRepository.java
  src/main/java/com/example/kaizenchat/repository/GroupChatOptionsRepository.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
Labels: enhancement, help wanted

#6 release_v1
  README.md
  pom.xml
  src/main/java/com/example/kaizenchat/controller/AuthController.java
  src/main/java/com/example/kaizenchat/dto/AddMemberToChatRequest.java
  src/main/java/com/example/kaizenchat/dto/DuoChatCreationRequest.java
  src/main/java/com/example/kaizenchat/dto/GroupChatCreationRequest.java
  src/main/java/com/example/kaizenchat/dto/RefreshTokenRequest.java
  src/main/java/com/example/kaizenchat/dto/UserLoginRequest.java
  src/main/java/com/example/kaizenchat/dto/UserRegistrationRequest.java
  src/main/java/com/example/kaizenchat/entity/ChatEntity.java
  src/main/java/com/example/kaizenchat/entity/GroupChatOptionsEntity.java
  src/main/java/com/example/kaizenchat/entity/MessageEntity.java
  src/main/java/com/example/kaizenchat/entity/RoleEntity.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
  src/main/java/com/example/kaizenchat/exception/ChatAlreadyExistsException.java
  src/main/java/com/example/kaizenchat/exception/ChatNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/InvalidRequestDataException.java
  src/main/java/com/example/kaizenchat/exception/MessageNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundInChatException.java
  src/main/java/com/example/kaizenchat/exception/UserViolationPermissionsException.java
  src/main/java/com/example/kaizenchat/model/ChatType.java
  src/main/java/com/example/kaizenchat/model/DuoChat.java
  src/main/java/com/example/kaizenchat/model/GroupChat.java
  src/main/java/com/example/kaizenchat/repository/ChatRepository.java
  src/main/java/com/example/kaizenchat/repository/GroupChatOptionsRepository.java
  src/main/java/com/example/kaizenchat/repository/MessageRepository.java
  src/main/java/com/example/kaizenchat/repository/RoleRepository.java
  src/main/java/com/example/kaizenchat/repository/UserRepository.java
  src/main/java/com/example/kaizenchat/security/SpringSecurityConfig.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTFilter.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTProvider.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTType.java
  src/main/java/com/example/kaizenchat/security/jwt/UserDetailsImpl.java
  src/main/java/com/example/kaizenchat/security/jwt/UserDetailsServiceImpl.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/MessageService.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/MessageServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/java/com/example/kaizenchat/websocket/WebSocketConfig.java
  src/main/resources/application.properties
Labels: documentation, enhancement, help wanted

#7 feature/TASK-10_add-method-for-deleting-messages
  src/main/java/com/example/kaizenchat/service/MessageService.java
  src/main/java/com/example/kaizenchat/service/impl/MessageServiceImpl.java
Labels: enhancement

#8 feature/TASK-11_create-user-controller
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
  src/main/java/com/example/kaizenchat/dto/UserUpdateRequest.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
Labels: documentation, enhancement, help wanted

#9 feature/TASK-12_develop-uploading-avatar-system
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
  src/main/java/com/example/kaizenchat/dto/UserUpdateRequest.java
  src/main/java/com/example/kaizenchat/exception/AvatarNotExistsException.java
  src/main/java/com/example/kaizenchat/model/Avatar.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/java/com/example/kaizenchat/utils/MultipartFileUtils.java
  src/main/resources/application.properties
Labels: documentation, enhancement, help wanted

#10 feature/TASK-13_create-controller-for-group-chats
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/dto/Action.java
  src/main/java/com/example/kaizenchat/dto/IncomingMessage.java
  src/main/java/com/example/kaizenchat/dto/OutgoingMessage.java
  src/main/java/com/example/kaizenchat/exception/JWTInvalidException.java
  src/main/java/com/example/kaizenchat/security/jwt/JWTProvider.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/websocket/CustomStompErrorHandler.java
  src/main/java/com/example/kaizenchat/websocket/WebSocketConfig.java
Labels: documentation, enhancement, help wanted

#12 feature/TASK-15_create-end-point-for-getting-chats
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/dto/Chat.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/MessageServiceImpl.java
Labels: documentation, enhancement

#13 feature/TASK-16_create-end-point-for-getting-user-duo-chats
  src/main/java/com/example/kaizenchat/controller/DuoChatController.java
Labels: enhancement

#15 feature/TASK-18_add-validation-and-exception-handlers
  README.md
  pom.xml
  src/main/java/com/example/kaizenchat/controller/AuthController.java
  src/main/java/com/example/kaizenchat/dto/DTOValidationHandler.java
  src/main/java/com/example/kaizenchat/dto/RefreshTokenRequest.java
  src/main/java/com/example/kaizenchat/dto/UserLoginRequest.java
  src/main/java/com/example/kaizenchat/dto/UserRegistrationRequest.java
  src/main/java/com/example/kaizenchat/dto/UserUpdateRequest.java
  src/main/java/com/example/kaizenchat/exception/ApiError.java
  src/main/java/com/example/kaizenchat/exception/AvatarNotExistsException.java
  src/main/java/com/example/kaizenchat/exception/ChatNotFoundException.java
  src/main/java/com/example/kaizenchat/exception/CustomExceptionHandler.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundException.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/MessageServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
Labels: documentation, enhancement

#16 feature/TASK-19_activate-error-handling
  src/main/java/com/example/kaizenchat/controller/UserController.java
Labels: help wanted
