Repository Kostia1507/KaizenChat, pull requests merged in 2023-05, with the labels that each got.

#17 feature/TASK-20_create_end_points_for_getting_messages
  src/main/java/com/example/kaizenchat/controller/DuoChatController.java
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/dto/LastMessagesRequest.java
Labels: enhancement

#19 refactor/TASK-20_create_end_points_for_getting_messages
  src/main/java/com/example/kaizenchat/controller/DuoChatController.java
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/exception/UserNotFoundInChatException.java
Labels: help wanted

#20 feature/TASK-21_add-moderation-to-duo-chats-controller
  README.md
  src/main/java/com/example/kaizenchat/controller/DuoChatController.java
  src/main/java/com/example/kaizenchat/dto/Action.java
  src/main/java/com/example/kaizenchat/dto/EditMessageRequest.java
  src/main/java/com/example/kaizenchat/dto/OutgoingMessage.java
Labels: documentation, enhancement, help wanted

#21 feature/TASK-22_refactor-auth-and-duo-chat-controllers
  README.md
  src/main/java/com/example/kaizenchat/controller/AuthController.java
  src/main/java/com/example/kaizenchat/controller/DuoChatController.java
  src/main/java/com/example/kaizenchat/exception/CustomExceptionHandler.java
  src/main/java/com/example/kaizenchat/exception/InvalidRequestDataException.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
Labels: documentation, enhancement

#23 feature/TASK-23_checking-phone-number-existence
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
Labels: documentation, enhancement

#24 feature/TASK-24_refactor-user-avatar-uploading
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
  src/main/java/com/example/kaizenchat/dto/UserRegistrationRequest.java
  src/main/java/com/example/kaizenchat/exception/CustomExceptionHandler.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/resources/images/chat_default_av.png
  src/main/resources/images/user_default_av.png
Labels: documentation, enhancement

#26 feature/TASK-25_add-group-chat-avatar-upload
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/entity/GroupChatOptionsEntity.java
  src/main/java/com/example/kaizenchat/exception/CustomExceptionHandler.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/java/com/example/kaizenchat/utils/AvatarUtils.java
  src/main/java/com/example/kaizenchat/utils/MultipartFileUtils.java
Labels: documentation, enhancement

#27 feature/TASK-26_group-chats-moderation
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/dto/KickMemberRequest.java
Labels: documentation, enhancement, help wanted

#29 hotfix/TASK-27_fix-exists-phone-number-end-point
  src/main/java/com/example/kaizenchat/controller/AuthController.java
  src/main/java/com/example/kaizenchat/controller/UserController.java
Labels: fix

#30 hotfix/TASK-28_fix-end-points-response-bodies
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
  src/main/java/com/example/kaizenchat/entity/MessageEntity.java
  src/main/java/com/example/kaizenchat/entity/UserEntity.java
Labels: documentation, fix

#31 hotfix/TASK-29_fix-duo-chats-fetch
  README.md
  src/main/java/com/example/kaizenchat/dto/Chat.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
Labels: documentation, fix

#32 feature/TASK-30_get-user-id-by-access-token
  README.md
  src/main/java/com/example/kaizenchat/controller/UserController.java
Labels: documentation, enhancement

#33 feature/TASK-31_check-permissions-before-subscription
  src/main/java/com/example/kaizenchat/websocket/CustomChannelInterceptor.java
  src/main/java/com/example/kaizenchat/websocket/WebSocketConfig.java
Labels: enhancement, help wanted

#34 feature/TASK-32_create-group-chats
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/dto/Chat.java
  src/main/java/com/example/kaizenchat/dto/GroupChatCreationRequest.java
  src/main/java/com/example/kaizenchat/repository/ChatRepository.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
Labels: documentation, enhancement

#36 release_v3
  README.md
  src/main/java/com/example/kaizenchat/controller/GroupChatController.java
  src/main/java/com/example/kaizenchat/controller/UserController.java
  src/main/java/com/example/kaizenchat/dto/AvatarDTO.java
  src/main/java/com/example/kaizenchat/dto/Chat.java
  src/main/java/com/example/kaizenchat/dto/GroupChatCreationRequest.java
  src/main/java/com/example/kaizenchat/exception/CustomExceptionHandler.java
  src/main/java/com/example/kaizenchat/model/Avatar.java
  src/main/java/com/example/kaizenchat/repository/ChatRepository.java
  src/main/java/com/example/kaizenchat/service/ChatService.java
  src/main/java/com/example/kaizenchat/service/UserService.java
  src/main/java/com/example/kaizenchat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/kaizenchat/service/impl/UserServiceImpl.java
  src/main/java/com/example/kaizenchat/utils/AvatarUtils.java
  src/main/java/com/example/kaizenchat/utils/MultipartFileUtils.java
  src/main/java/com/example/kaizenchat/websocket/CustomChannelInterceptor.java
  src/main/java/com/example/kaizenchat/websocket/WebSocketConfig.java
  src/main/resources/images/chat_default_av.png
  src/main/resources/images/chat_default_av.txt
  src/main/resources/images/user_default_av.png
  src/main/resources/images/user_default_av.txt
Labels: documentation, enhancement, fix
